apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: core

resources:
- ../../kustomize/service1/overlays/production

configMapGenerator:
- name: feature-flags
  behavior: replace
  literals:
  - "SWIMLANE_EnableHA=true"
