name: Manifest Generation
run-name: Manifest Generation

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Version artifact version (Ex: 0.1.0)'
        type: string
        required: true
      environment:
        description: 'Deployment'
        required: true
        type: choice
        options:
        - cloud-staging
        - cloud-production

jobs:
  template-manifests: 
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v3

    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - name: Kustomize Build
      run: |
        cd deployments/${{ inputs.environment }}
        kustomize build . > "${{ inputs.environment }}-${{ inputs.version-tag }}.yaml"

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.environment }}-${{ inputs.version-tag }}.yaml
        path: deployments/${{ inputs.environment }}-${{ inputs.version-tag }}.yaml
        retention-days: 5