name: Manifest Generation
run-name: Manifest Generation

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Version artifact version (Ex: 0.1.0)'
        type: string
        required: true
      environment:
        description: 'Deployment'
        required: true
        type: choice
        options:
        - cloud-staging
        - cloud-production

jobs:
  template-manifests: 
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v3

    - name: Install Kustomize
      run: |
        mkdir -p .bin
        cd .bin
        wget "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.0.1/kustomize_v5.0.1_linux_amd64.tar.gz"
        tar -zxvf kustomize_v5.0.1_linux_amd64.tar.gz
        ./kustomize version

    - name: Kustomize Build
      run: |
        .bin/kustomize build deployments/${{ inputs.environment }} > "${{ inputs.environment }}-${{ inputs.version-tag }}.yaml"

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.environment }}-${{ inputs.version-tag }}.yaml
        path: deployments/${{ inputs.environment }}-${{ inputs.version-tag }}.yaml
        retention-days: 5