name: Manifest Generation
run-name: Manifest Generation

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Version artifact version (Ex: 0.1.0)'
        type: string
        required: true
      environment:
        description: 'Deployment'
        required: true
        type: choice
        options:
        - cloud-staging
        - cloud-production

jobs:
  template-manifests: 
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v3

    - name: Kustomize Github Action
      uses: karancode/kustomize-github-action@v1.3.2
      with:
        kustomize_build_dir: 'deployments/${{ inputs.environment }}'
        kustomize_output_file: "${{ inputs.environment }}-${{ inputs.version-tag }}.yaml"

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.environment }}-${{ inputs.version-tag }}.yaml
        path: ${{ inputs.environment }}-${{ inputs.version-tag }}.yaml
        retention-days: 5